### ISSUE TITLE
Add TS3 support

### ISSUE THREAD

**Issue by Stalinko** [prismatic-io/embedded#10]
Hi guys.

For historical reasons we still have TS 3.9 in our project.
And we've got troubles when tried it install this embedded component because it is designed for TS 4.

Actually there are just 2 lines in phrases.ts which use TS 4 specific features.
I made a quick fix in my fork:
https://github.com/prismatic-io/embedded/commit/40b010aa8acc4aa471303c9afa54f37a13b9c8ab

But probably it's not the ideal solution.
Maybe you can make an official fork (or tag, or version, IDK how to call this) with TS 3 support? :)

**Comment by taylorreece** [comment]
Hey @Stalinko , it looks like the TS4 syntax you were running into is related to i18n, and has been moved into its own project - https://github.com/prismatic-io/translations. Are you still looking to support TS3 for i18n? If so, forking the `@prismatic-io/translations` package will be needed.

**Comment by Stalinko** [comment]
hey @taylorreece 

nah, this is not necessary anymore. We've upgraded to TS4 and also built our own integration marketplace without embedded :)
