### ISSUE TITLE
Bug: it's impossible to call "prismatic.init()" from outside of the package in TypeScript

### ISSUE THREAD

**Issue by Stalinko** [prismatic-io/embedded#5]
Our app is written in TypeScript.
That's why we installed this package via the recommended npm-way.

And this is where I've got into troubles:

```ts
import prismatic from '@prismatic-io/embedded';
const PRISMATIC_MARKETPLACE_CONFIGURATION = {
  theme: 'LIGHT',
};
prismatic.init(PRISMATIC_MARKETPLACE_CONFIGURATION);
```

This simple script is impossible because `prismatic.init()` function requires the argument of `InitProps` type and I get incompatible types error. But this type is not exported from outside of the package, hence I can't import it and use it.
That's why I basically can't call the init-method if I develop in TypeScript. I was able to bypass the issue via "ts-ignore" but that's nasty.

Hopefully you can fix this issue and export all the types which are necessary to use your API methods. This is not the case only for `init()`.

**Comment by bkegley** [comment]
@Stalinko Thanks for the report. I believe the issue is that TypeScript infers the value of `PRISMATIC_MARKETPLACE_CONFIGURATION.theme` as `string` instead of the string literal that you're hoping. To tell TS that you want it to use the string literal you'll need to add `as const`. It also works if you define the configuration inline as TS is expecting those enum values.

Both the following should get it to compile without the `@ts--ignore`:
```ts
import prismatic from '@prismatic-io/embedded';
const PRISMATIC_MARKETPLACE_CONFIGURATION = {
  theme: 'LIGHT' as const,
};
prismatic.init(PRISMATIC_MARKETPLACE_CONFIGURATION);
```

```ts
import prismatic from '@prismatic-io/embedded';

prismatic.init({
  theme: 'LIGHT'
});
```

**Comment by Stalinko** [comment]
hey @bkegley 

very smart workaround, I didn't know it could be done with "as const" casting, but it really works.

However we already made a fork which exports that type) and solved the issue this way.

Probably you should address this case in your docs if you aren't going to export the types.

**Comment by jasoncomes** [comment]
Hey @Stalinko - When you have a chance, could you let us know if these types are sufficient enough for your setup.  Type include, `phases, translation, options, theme, and configuration screens`.

https://github.com/prismatic-io/embedded/pull/9

**Comment by Stalinko** [comment]
that looks awesome @jasoncomes 
this is exactly what I was hinting about

and yes it solves the problem mentioned in this ticket
thank you
