### ISSUE TITLE
prismatic.showIntegrations is throwing a 404 in iframe embed mode

### ISSUE THREAD

**Issue by FatehAK** [prismatic-io/embedded#64]
On using the `showIntegrations` method of the SDK, I'm getting a 404 not found page. But when I copy the iframe url and paste in a new browser tab it opens up properly. 

Please let me know if any further details are required.

![image](https://github.com/prismatic-io/embedded/assets/34565559/9fc648cd-7c87-4533-80f9-b01f321360cf)

**Comment by taylorreece** [comment]
Hi @FatehAK , sorry you're running into that! I can replicate that behavior under two conditions:
- If I run `prismatic.init()`, but do not `await` a call of `prismatic.authenticate()` before trying to run a `prismatic.showIntegrations()`. In that case, the SDK doesn't have a valid JWT in hand before running `prismatic.showIntegrations()`, resulting in a 404 page.
- If I run `prismatic.showIntegrations` for a customer who does not have embedded designer enabled.

Check if either of those are true. A quick way to check if a JWT is set is to look at the iframe that is embedded - the URL of the iframe should have a JWT in its search parameters.

I'm going to add #66 to help throw a more intuitive error for both of these situations.

**Comment by taylorreece** [comment]
These errors should be handled more gracefully by #66 . Please reach out if you have any more trouble embedding marketplace!
